/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    members: MemberAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    categories: Category;
    tags: Tag;
    forms: Form;
    'form-submissions': FormSubmission;
    redirects: Redirect;
    partners: Partner;
    'ingredient-categories': IngredientCategory;
    ingredients: Ingredient;
    technologies: Technology;
    services: Service;
    certifications: Certification;
    'case-studies': CaseStudy;
    faqs: Faq;
    members: Member;
    'gated-documents': GatedDocument;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'ingredient-categories': IngredientCategoriesSelect<false> | IngredientCategoriesSelect<true>;
    ingredients: IngredientsSelect<false> | IngredientsSelect<true>;
    technologies: TechnologiesSelect<false> | TechnologiesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'gated-documents': GatedDocumentsSelect<false> | GatedDocumentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('vi' | 'en') | ('vi' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    branding: Branding;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    branding: BrandingSelect<false> | BrandingSelect<true>;
  };
  locale: 'vi' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Member;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Phân quyền truy cập admin.
   */
  role: 'admin' | 'editor' | 'viewer';
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Văn bản thay thế (a11y/SEO).
   */
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Để trống sẽ tự tạo từ tiêu đề.
   */
  slug?: string | null;
  hero?: (number | null) | Media;
  /**
   * Bố cục trang ghép từ các block tái dùng.
   */
  layout?:
    | (
        | HeroBlock
        | RichTextBlock
        | StatsBlock
        | FeatureGridBlock
        | GalleryBlock
        | CTABlock
        | VideoEmbedBlock
        | LogoCloudBlock
      )[]
    | null;
  /**
   * Meta cho công cụ tìm kiếm & mạng xã hội.
   */
  seo?: {
    /**
     * Thẻ <title>. Bỏ trống dùng tiêu đề mặc định.
     */
    title?: string | null;
    /**
     * Meta description (~155 ký tự).
     */
    description?: string | null;
    /**
     * Ảnh Open Graph (1200×630).
     */
    image?: (number | null) | Media;
    /**
     * Canonical URL (tùy chọn).
     */
    canonical?: string | null;
    /**
     * Chặn index trang này.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  heading: string;
  subheading?: string | null;
  media?: (number | null) | Media;
  links?:
    | {
        label: string;
        href: string;
        style?: ('primary' | 'outline' | 'ghost') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  heading?: string | null;
  items?:
    | {
        value: string;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  heading?: string | null;
  columns?: ('2' | '3' | '4') | null;
  items?:
    | {
        /**
         * Tên icon (lucide) hoặc emoji.
         */
        icon?: string | null;
        image?: (number | null) | Media;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  layout?: ('grid' | 'carousel' | 'masonry') | null;
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  heading: string;
  text?: string | null;
  background?: ('tint' | 'solid' | 'image') | null;
  image?: (number | null) | Media;
  links?:
    | {
        label: string;
        href: string;
        style?: ('primary' | 'outline' | 'ghost') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock".
 */
export interface VideoEmbedBlock {
  /**
   * YouTube/Vimeo/MP4 URL.
   */
  url: string;
  poster?: (number | null) | Media;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlock".
 */
export interface LogoCloudBlock {
  heading?: string | null;
  logos?:
    | {
        logo: number | Media;
        name?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoCloud';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Để trống sẽ tự tạo từ tiêu đề.
   */
  slug?: string | null;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cover?: (number | null) | Media;
  author?: (number | null) | User;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  publishedAt?: string | null;
  /**
   * Meta cho công cụ tìm kiếm & mạng xã hội.
   */
  seo?: {
    /**
     * Thẻ <title>. Bỏ trống dùng tiêu đề mặc định.
     */
    title?: string | null;
    /**
     * Meta description (~155 ký tự).
     */
    description?: string | null;
    /**
     * Ảnh Open Graph (1200×630).
     */
    image?: (number | null) | Media;
    /**
     * Canonical URL (tùy chọn).
     */
    canonical?: string | null;
    /**
     * Chặn index trang này.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Để trống sẽ tự tạo từ tiêu đề.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * Để trống sẽ tự tạo từ tiêu đề.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | {
        /**
         * Khóa dữ liệu (vd: email).
         */
        name: string;
        label: string;
        type?: ('text' | 'email' | 'textarea' | 'number' | 'tel' | 'checkbox' | 'select') | null;
        required?: boolean | null;
        options?:
          | {
              label?: string | null;
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Gửi thông báo khi có lượt gửi form.
   */
  emails?:
    | {
        to: string;
        subject?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Đường dẫn nguồn, vd /cu
   */
  from: string;
  /**
   * Đường dẫn đích, vd /moi
   */
  to: string;
  type?: ('301' | '302') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  /**
   * Mã/tên quốc gia, vd JP.
   */
  country?: string | null;
  logo?: (number | null) | Media;
  website?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredient-categories".
 */
export interface IngredientCategory {
  id: number;
  name: string;
  /**
   * Để trống sẽ tự tạo từ tiêu đề.
   */
  slug?: string | null;
  scope?: ('supplement' | 'cosmetic' | 'both') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients".
 */
export interface Ingredient {
  id: number;
  name: string;
  /**
   * Để trống sẽ tự tạo từ tiêu đề.
   */
  slug?: string | null;
  subtitle?: string | null;
  type: 'supplement' | 'cosmetic';
  category?: (number | null) | IngredientCategory;
  /**
   * Mã quốc gia, vd JP.
   */
  originCountry?: string | null;
  /**
   * Thương hiệu OEM.
   */
  brandName?: string | null;
  partner?: (number | null) | Partner;
  moq?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Mỗi mục là một lợi ích.
   */
  benefits?: string[] | null;
  /**
   * Ứng dụng / dạng bào chế.
   */
  applications?: string[] | null;
  /**
   * Nhãn chứng nhận hiển thị trên thẻ (Halal, Non-GMO…).
   */
  badges?: string[] | null;
  featuredImage?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  technologies?: (number | Technology)[] | null;
  specs?:
    | {
        label: string;
        value: string;
        unit?: string | null;
        display?: ('text' | 'number' | 'bar' | 'donut') | null;
        /**
         * 0–100 (cho dạng bar/donut).
         */
        percent?: number | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  /**
   * Meta cho công cụ tìm kiếm & mạng xã hội.
   */
  seo?: {
    /**
     * Thẻ <title>. Bỏ trống dùng tiêu đề mặc định.
     */
    title?: string | null;
    /**
     * Meta description (~155 ký tự).
     */
    description?: string | null;
    /**
     * Ảnh Open Graph (1200×630).
     */
    image?: (number | null) | Media;
    /**
     * Canonical URL (tùy chọn).
     */
    canonical?: string | null;
    /**
     * Chặn index trang này.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies".
 */
export interface Technology {
  id: number;
  name: string;
  /**
   * Để trống sẽ tự tạo từ tiêu đề.
   */
  slug?: string | null;
  tagline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cơ chế hoạt động.
   */
  mechanism?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  videoUrl?: string | null;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  specs?:
    | {
        label: string;
        value: string;
        unit?: string | null;
        display?: ('text' | 'number' | 'bar' | 'donut') | null;
        /**
         * 0–100 (cho dạng bar/donut).
         */
        percent?: number | null;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  /**
   * Meta cho công cụ tìm kiếm & mạng xã hội.
   */
  seo?: {
    /**
     * Thẻ <title>. Bỏ trống dùng tiêu đề mặc định.
     */
    title?: string | null;
    /**
     * Meta description (~155 ký tự).
     */
    description?: string | null;
    /**
     * Ảnh Open Graph (1200×630).
     */
    image?: (number | null) | Media;
    /**
     * Canonical URL (tùy chọn).
     */
    canonical?: string | null;
    /**
     * Chặn index trang này.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Để trống sẽ tự tạo từ tiêu đề.
   */
  slug?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Tên icon (lucide).
   */
  icon?: string | null;
  image?: (number | null) | Media;
  features?: string[] | null;
  order?: number | null;
  /**
   * Meta cho công cụ tìm kiếm & mạng xã hội.
   */
  seo?: {
    /**
     * Thẻ <title>. Bỏ trống dùng tiêu đề mặc định.
     */
    title?: string | null;
    /**
     * Meta description (~155 ký tự).
     */
    description?: string | null;
    /**
     * Ảnh Open Graph (1200×630).
     */
    image?: (number | null) | Media;
    /**
     * Canonical URL (tùy chọn).
     */
    canonical?: string | null;
    /**
     * Chặn index trang này.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  title: string;
  kind?: ('certificate' | 'stat' | 'award') | null;
  /**
   * Vd: GMP / 23 / 14.
   */
  value?: string | null;
  /**
   * Vd: dự án R&D.
   */
  suffix?: string | null;
  image?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Câu chuyện thương hiệu đã đồng kiến tạo cùng Bioscope.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  brand: string;
  /**
   * Để trống sẽ tự tạo từ tiêu đề.
   */
  slug?: string | null;
  /**
   * Đối tác nguyên liệu hoặc công nghệ áp dụng (vd GC Rieber Oils, Phytosome ướt).
   */
  partner?: string | null;
  industry?: ('Thực phẩm chức năng' | 'Dược phẩm' | 'Mỹ phẩm' | 'Dinh dưỡng') | null;
  summary?: string | null;
  /**
   * vd 500K USD, 70%+, #1
   */
  kpi?: string | null;
  kpiLabel?: string | null;
  problem?: string | null;
  solution?: string | null;
  /**
   * Mỗi mục là một kết quả đo lường được.
   */
  results?: string[] | null;
  coCreateSteps?: string[] | null;
  testimonial?: string | null;
  /**
   * Nhãn hiển thị trên thẻ (vd Đồng kiến tạo, Dầu & Omega).
   */
  tags?: string[] | null;
  coverImage?: (number | null) | Media;
  featured?: boolean | null;
  order?: number | null;
  /**
   * Meta cho công cụ tìm kiếm & mạng xã hội.
   */
  seo?: {
    /**
     * Thẻ <title>. Bỏ trống dùng tiêu đề mặc định.
     */
    title?: string | null;
    /**
     * Meta description (~155 ký tự).
     */
    description?: string | null;
    /**
     * Ảnh Open Graph (1200×630).
     */
    image?: (number | null) | Media;
    /**
     * Canonical URL (tùy chọn).
     */
    canonical?: string | null;
    /**
     * Chặn index trang này.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Hỏi đáp hiển thị ở trang Câu hỏi thường gặp và trang Liên hệ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: ('ingredients' | 'solutions' | 'support') | null;
  showOnContact?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  company: string;
  contactName: string;
  phone?: string | null;
  status?: ('pending' | 'approved' | 'rejected') | null;
  approvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'members';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gated-documents".
 */
export interface GatedDocument {
  id: number;
  title: string;
  docType?: ('COA' | 'spec_sheet' | 'quote' | 'brochure') | null;
  file: number | Media;
  visibility?: ('approved_members' | 'specific') | null;
  allowedMembers?: (number | Member)[] | null;
  relatesTo?: (number | Ingredient)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'ingredient-categories';
        value: number | IngredientCategory;
      } | null)
    | ({
        relationTo: 'ingredients';
        value: number | Ingredient;
      } | null)
    | ({
        relationTo: 'technologies';
        value: number | Technology;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'gated-documents';
        value: number | GatedDocument;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        videoEmbed?: T | VideoEmbedBlockSelect<T>;
        logoCloud?: T | LogoCloudBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  media?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  heading?: T;
  columns?: T;
  items?:
    | T
    | {
        icon?: T;
        image?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  layout?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  background?: T;
  image?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock_select".
 */
export interface VideoEmbedBlockSelect<T extends boolean = true> {
  url?: T;
  poster?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlock_select".
 */
export interface LogoCloudBlockSelect<T extends boolean = true> {
  heading?: T;
  logos?:
    | T
    | {
        logo?: T;
        name?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  cover?: T;
  author?: T;
  categories?: T;
  tags?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        name?: T;
        label?: T;
        type?: T;
        required?: T;
        options?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  confirmationMessage?: T;
  emails?:
    | T
    | {
        to?: T;
        subject?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  logo?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredient-categories_select".
 */
export interface IngredientCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  scope?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients_select".
 */
export interface IngredientsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  subtitle?: T;
  type?: T;
  category?: T;
  originCountry?: T;
  brandName?: T;
  partner?: T;
  moq?: T;
  description?: T;
  benefits?: T;
  applications?: T;
  badges?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  technologies?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        unit?: T;
        display?: T;
        percent?: T;
        id?: T;
      };
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies_select".
 */
export interface TechnologiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  mechanism?: T;
  featuredImage?: T;
  videoUrl?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        unit?: T;
        display?: T;
        percent?: T;
        id?: T;
      };
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  icon?: T;
  image?: T;
  features?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  value?: T;
  suffix?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  brand?: T;
  slug?: T;
  partner?: T;
  industry?: T;
  summary?: T;
  kpi?: T;
  kpiLabel?: T;
  problem?: T;
  solution?: T;
  results?: T;
  coCreateSteps?: T;
  testimonial?: T;
  tags?: T;
  coverImage?: T;
  featured?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  showOnContact?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  company?: T;
  contactName?: T;
  phone?: T;
  status?: T;
  approvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gated-documents_select".
 */
export interface GatedDocumentsSelect<T extends boolean = true> {
  title?: T;
  docType?: T;
  file?: T;
  visibility?: T;
  allowedMembers?: T;
  relatesTo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  logo?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  contact?: {
    address?: string | null;
    phone?: string | null;
    email?: string | null;
    mst?: string | null;
  };
  social?:
    | {
        platform?: ('facebook' | 'linkedin' | 'youtube' | 'instagram' | 'zalo' | 'x' | 'tiktok') | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * ID đo lường (để trống nếu chưa dùng).
   */
  tracking?: {
    ga4?: string | null;
    gtm?: string | null;
    pixel?: string | null;
  };
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header?:
    | {
        label: string;
        url: string;
        children?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footer?:
    | {
        label: string;
        url: string;
        children?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Whitelabel: logo, màu sắc, bo góc cho trang quản trị.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding".
 */
export interface Branding {
  id: number;
  brandName?: string | null;
  /**
   * Logo hiển thị ở đăng nhập & menu.
   */
  logo?: (number | null) | Media;
  loginSubtitle?: string | null;
  /**
   * Màu thương hiệu chính (hex).
   */
  primaryColor?: string | null;
  primaryDark?: string | null;
  accentColor?: string | null;
  /**
   * Bo góc (px).
   */
  radius?: number | null;
  /**
   * Font CSS, vd: "Be Vietnam Pro", sans-serif.
   */
  fontFamily?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  logoDark?: T;
  contact?:
    | T
    | {
        address?: T;
        phone?: T;
        email?: T;
        mst?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  tracking?:
    | T
    | {
        ga4?: T;
        gtm?: T;
        pixel?: T;
      };
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  footer?:
    | T
    | {
        label?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding_select".
 */
export interface BrandingSelect<T extends boolean = true> {
  brandName?: T;
  logo?: T;
  loginSubtitle?: T;
  primaryColor?: T;
  primaryDark?: T;
  accentColor?: T;
  radius?: T;
  fontFamily?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}