import { homeImages } from "./home-images";

/** 4 sản phẩm nổi bật trang chủ — khớp layout mockup example */
export const homeFeaturedIngredients = [
  {
    slug: "curcumin-extract-95",
    name: { en: "Curcumin Extract 95%", vi: "Chiết xuất Curcumin 95%" },
    subtitle: { en: "Curcuminoids 95%", vi: "Curcuminoids 95%" },
    origin: { en: "India", vi: "Ấn Độ" },
    moq: "25 kg",
    image: homeImages.ingredients.curcumin,
    badges: ["Halal", "Non-GMO", "GMP"],
  },
  {
    slug: "omega-3-fish-oil",
    name: { en: "Omega 3 Fish Oil", vi: "Dầu cá Omega 3" },
    subtitle: { en: "TG Form – 90%", vi: "Dạng TG – 90%" },
    origin: { en: "Norway", vi: "Na Uy" },
    moq: "20 kg",
    image: homeImages.ingredients.omega3,
    badges: ["IFOS 5-Star", "GMP", "Halal"],
  },
  {
    slug: "argentina-collagen-peptide",
    name: { en: "Collagen Peptide", vi: "Collagen Peptide" },
    subtitle: { en: "Hydrolyzed Collagen", vi: "Collagen thủy phân" },
    origin: { en: "France", vi: "Pháp" },
    moq: "25 kg",
    image: homeImages.ingredients.collagen,
    badges: ["Halal", "BSE/TSE Free", "GMP"],
  },
  {
    slug: "nmn",
    name: { en: "NMN", vi: "NMN" },
    subtitle: { en: "Nicotinamide Mononucleotide", vi: "Nicotinamide Mononucleotide" },
    origin: { en: "Japan", vi: "Nhật Bản" },
    moq: "10 kg",
    image: homeImages.ingredients.nmn,
    badges: ["≥ 99% Purity", "Non-GMO", "GMP"],
  },
  {
    slug: "coenzyme-q10",
    name: { en: "Coenzyme Q10", vi: "Coenzyme Q10" },
    subtitle: { en: "Ubiquinone 98%", vi: "Ubiquinone 98%" },
    origin: { en: "Japan", vi: "Nhật Bản" },
    moq: "5 kg",
    image: homeImages.ingredients.coq10,
    badges: ["Non-GMO", "GMP", "Halal"],
  },
  {
    slug: "resveratrol-98",
    name: { en: "Resveratrol 98%", vi: "Resveratrol 98%" },
    subtitle: { en: "Polygonum cuspidatum", vi: "Hổ trượng" },
    origin: { en: "China", vi: "Trung Quốc" },
    moq: "10 kg",
    image: homeImages.ingredients.resveratrol,
    badges: ["≥ 98% Purity", "Non-GMO", "GMP"],
  },
  {
    slug: "ashwagandha-extract",
    name: { en: "Ashwagandha Extract", vi: "Chiết xuất Ashwagandha" },
    subtitle: { en: "Withanolides 5%", vi: "Withanolides 5%" },
    origin: { en: "India", vi: "Ấn Độ" },
    moq: "25 kg",
    image: homeImages.ingredients.ashwagandha,
    badges: ["Organic", "Halal", "GMP"],
  },
  {
    slug: "vitamin-c-coated",
    name: { en: "Vitamin C (Coated)", vi: "Vitamin C (bao tan chậm)" },
    subtitle: { en: "Sustained-release 99%", vi: "Phóng thích chậm 99%" },
    origin: { en: "Switzerland", vi: "Thụy Sĩ" },
    moq: "25 kg",
    image: homeImages.ingredients.vitaminC,
    badges: ["Non-GMO", "GMP", "Kosher"],
  },
  {
    slug: "hyaluronic-acid",
    name: { en: "Hyaluronic Acid", vi: "Hyaluronic Acid" },
    subtitle: { en: "Low molecular weight", vi: "Phân tử lượng thấp" },
    origin: { en: "Japan", vi: "Nhật Bản" },
    moq: "5 kg",
    image: homeImages.ingredients.hyaluronic,
    badges: ["Halal", "Non-GMO", "GMP"],
  },
  {
    slug: "magnesium-bisglycinate",
    name: { en: "Magnesium Bisglycinate", vi: "Magnesium Bisglycinate" },
    subtitle: { en: "Chelated · High absorption", vi: "Chelate · Hấp thu cao" },
    origin: { en: "Germany", vi: "Đức" },
    moq: "25 kg",
    image: homeImages.ingredients.magnesium,
    badges: ["Non-GMO", "GMP", "Halal"],
  },
] as const;
